version: '3.8'

services:
  app:
    build: .
    container_name: prestagedswap_app
    restart: unless-stopped
    volumes:
      - ./src:/var/www/html/src
      - ./public:/var/www/html/public
    ports:
      - "8080:9000"
    depends_on:
      - db
    env_file:
      - .env
    environment:
      POSTGRES_HOST: db
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      

  db:
    image: postgres:16
    container_name: prestagedswap_db
    restart: unless-stopped
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:

